CREATE TABLE IF NOT EXISTS `llx_c_commercial_category`(
`rowid`INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
`code`VARCHAR(50) NOT NULL,
`label`VARCHAR(255) NOT NULL,
`active`TINYINT NOT NULL DEFAULT '1'
)ENGINE=innodb DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
