CREATE TABLE IF NOT EXISTS `llx_dynamicprices_product_cost_log` (
	`rowid` integer AUTO_INCREMENT PRIMARY KEY,
	`entity` integer NOT NULL DEFAULT 1,
	`fk_product` integer NOT NULL,
	`fk_product_cost` integer NULL,
	`old_dynamic_cost_price` double(24,8) NULL,
	`new_dynamic_cost_price` double(24,8) NULL,
	`dolibarr_cost_price_snapshot` double(24,8) NULL,
	`pmp_snapshot` double(24,8) NULL,
	`source_type` varchar(32) NULL,
	`source_value` double(24,8) NULL,
	`source_details` text NULL,
	`fk_rule` integer NULL,
	`rule_code` varchar(64) NULL,
	`coefficient` double(24,8) NULL,
	`rounding_rule` varchar(32) NULL,
	`calculation_context` varchar(32) NULL,
	`object_type_source` varchar(32) NULL,
	`fk_object_source` integer NULL,
	`diff_abs` double(24,8) NULL,
	`diff_percent` double(24,8) NULL,
	`date_creation` datetime NOT NULL,
	`fk_user_author` integer NULL,
	`note_private` text NULL,
	`import_key` varchar(14) NULL
) ENGINE=innodb;
