CREATE TABLE IF NOT EXISTS `llx_dynamicprices_product_cost` (
	`rowid` integer AUTO_INCREMENT PRIMARY KEY,
	`entity` integer NOT NULL DEFAULT 1,
	`fk_product` integer NOT NULL,
	`dynamic_cost_price` double(24,8) NULL,
	`price_base_type` varchar(3) DEFAULT 'HT',
	`currency_code` varchar(3) NULL,
	`source_type` varchar(32) NULL,
	`source_value` double(24,8) NULL,
	`source_details` text NULL,
	`fk_rule` integer NULL,
	`rule_code` varchar(64) NULL,
	`coefficient` double(24,8) NULL,
	`rounding_rule` varchar(32) NULL,
	`calculation_hash` varchar(64) NULL,
	`calculation_status` smallint DEFAULT 1,
	`calculation_message` text NULL,
	`date_calculation` datetime NULL,
	`date_creation` datetime NOT NULL,
	`tms` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`fk_user_author` integer NULL,
	`fk_user_modif` integer NULL,
	`import_key` varchar(14) NULL,
	`status` smallint DEFAULT 1
) ENGINE=innodb;
